eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
    lease-expiration-duration-in-seconds: 100
    lease-renewal-interval-in-seconds: 100
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://liu:123456@127.0.0.1:8071/eureka
server:
  port: 8083
spring:
#  mail:
#    host: smtp.qq.com #发送邮件服务器
#    username: 2544853876 #QQ邮箱
#    password: cqswzucojcbodhhc #客户端授权码
#    protocol: smtp #发送邮件协议
#    properties.mail.smtp.auth: true
#    properties.mail.smtp.port: 465 #端口号465或587
#    properties.mail.display.sendmail: Javen #可以任意
#    properties.mail.display.sendname: Spring Boot Guide Email #可以任意
#    properties.mail.smtp.starttls.enable: true
#    properties.mail.smtp.starttls.required: true
#    properties.mail.smtp.ssl.enable: true
#    default-encoding: utf-8
#    from: 2544853876@qq.com #与上面的username保持一致
  mail:
    host: smtp.163.com
    username: liubenwwei00@163.com
    password: liubenwei02
    protocol: smtp
    properties.mail.smtp.auth: true
    properties.mail.smtp.port: 994 #465或者994
    properties.mail.display.sendmail: Javen
    properties.mail.display.sendname: Spring Boot Guide Email
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8
    from: liubenwwei00@163.com
  application:
    name: common
  redis:
    database: 0
    host: 49.235.221.50
    port: 6379
    password: liubenwei
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 1
#  mail:
#    host: smtp.qq.com
#    username: 2544853876@qq.com
#    password: gsbcgszmaltrdjff
#    properties:
#      mail:
#        smtp:
#          ssl:
#            enable: true
#          socketFactory:
#            port: 465
#            class: javax.net.ssl.SSLSocketFactory
#          auth: true
#          starttls:
#            enable: true
#            required: true
#    default-encoding: UTF-8
#    port: 465
#    from: 2544853876@qq.com
